name: torgo
version: 1.4.2
summary: A Logo interpreter written in Java.
description: A Logo interpreter written in Java.
grade: stable

confinement: strict

apps:
  torgo:
    command: bin/wrapper
    plugs: [home, x11, opengl, network, unity7]

parts:
  torgo:
    plugin: maven
    source: .
    maven-options:
      - -DskipTests
    stage-packages:
      - fontconfig-config
      - default-jdk
      - fonts-dejavu-extra
      - fonts-ipafont-gothic
    stage:
      - -lib/x86_64-linux-gnu/libdbus-1**
    snap:
      - -lib/x86_64-linux-gnu/libdbus-1**
#    after: [desktop-glib-only]
    organize:
      ../build/target/lib: jar/lib
      ../build/wrapper: bin/
      ../build/torgo-mime.xml: usr/share/mime/packages/torgo-mime.xml
