#!/bin/bash

# Not good, needed for fontconfig
export XDG_DATA_HOME=$SNAP/usr/share
# Font Config
export FONTCONFIG_PATH=$SNAP/etc/fonts/config.d
export FONTCONFIG_FILE=$SNAP/etc/fonts/fonts.conf
export HOME=$SNAP_USER_DATA

$SNAP/usr/lib/jvm/default-java/bin/java -Dsnapd=false -Duser.home=$HOME -Dsun.java2d.opengl=true -jar $SNAP/jar/torgo-1.0.6.jar
